In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("./data/gemstone.csv")

In [3]:
data.drop(columns='id', axis=1, inplace=True)

In [4]:
data.head()

carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [5]:
X = data.drop('price', axis=1)


In [6]:
X

carat        cut color clarity  depth  table     x     y     z
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 9 columns]

In [7]:
y = data['price']

In [8]:
y

0         13619
1         13387
2          2772
3           666
4         14453
          ...  
193568     1130
193569     2874
193570     3036
193571      681
193572     2258
Name: price, Length: 193573, dtype: int64

In [9]:
categorical_col = X.select_dtypes(include='object').columns

In [10]:
numerical_col = X.select_dtypes(exclude='object').columns

In [11]:
X.select_dtypes(include='object')

cut color clarity
0         Premium     F     VS2
1       Very Good     J     SI2
2           Ideal     G     VS1
3           Ideal     G     VS1
4         Premium     G     VS2
...           ...   ...     ...
193568      Ideal     D    VVS2
193569    Premium     G    VVS2
193570  Very Good     F     SI1
193571  Very Good     D     SI1
193572       Good     E     SI2

[193573 rows x 3 columns]

In [12]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [15]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [16]:
num_pipeline = Pipeline(

    steps= [
        ('imputer',SimpleImputer()),
        ('scaler',StandardScaler())
    ]
)

In [17]:
cat_pipeline = Pipeline(

    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder', OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories]))
    ]
)

In [18]:
preprocessor = ColumnTransformer(
    [
        ('num_pipeline',num_pipeline, numerical_col),
        ('cat_pipeline',cat_pipeline,categorical_col)
    ]
)

In [21]:
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('ordinalencoder',
                                                  OrdinalEncoder(categories=[['Fair',
                                                                              'Good',
                                                                              'Very '
                                                                              'Good',
                                                                              'Premium',
                                                                              'Ideal'],
                                                                             ['D',
                                                                              'E',
                                                                              'F',
                                                                              'G',
                                                                              'H',
                                                                              'I',
                                                                              'J'],
                                                                             ['I1',
                                                                              'SI2',
                                                                              'SI1',
                                                                              'VS2',
                                                                              'VS1',
                                                                              'VVS2',
                                                                              'VVS1',
                                                                              'IF']]))]),
                                 Index(['cut', 'color', 'clarity'], dtype='object'))])

In [22]:
## Train Test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=30)

In [23]:
preprocessor.fit_transform(X_train)

array([[-0.97543926, -0.84960654, -0.12153081, ...,  4.        ,
         5.        ,  5.        ],
       [ 0.2351953 ,  1.83363716, -0.12153081, ...,  1.        ,
         1.        ,  2.        ],
       [ 0.49461699,  0.81585507,  0.39980029, ...,  3.        ,
         3.        ,  4.        ],
       ...,
       [ 0.45138004,  1.55606023, -0.6428619 , ...,  1.        ,
         3.        ,  2.        ],
       [ 0.66756478, -1.77486298,  1.44246248, ...,  4.        ,
         3.        ,  4.        ],
       [ 0.25681377,  0.81585507, -0.12153081, ...,  4.        ,
         3.        ,  2.        ]])

In [25]:
preprocessor.transform(X_test)

array([[-0.56468825, -0.94213218, -0.6428619 , ...,  3.        ,
         1.        ,  3.        ],
       [-0.17555571,  1.00090636, -0.12153081, ...,  2.        ,
         4.        ,  2.        ],
       [-1.06191316,  0.2607012 , -0.12153081, ...,  4.        ,
         4.        ,  7.        ],
       ...,
       [-0.19717419, -3.34779894,  1.44246248, ...,  3.        ,
         6.        ,  3.        ],
       [-0.82410994, -0.20192702, -0.12153081, ...,  4.        ,
         3.        ,  2.        ],
       [ 2.61322747, -0.75708089,  1.44246248, ...,  3.        ,
         6.        ,  3.        ]])

In [26]:
preprocessor.get_feature_names_out()

array(['num_pipeline__carat', 'num_pipeline__depth',
       'num_pipeline__table', 'num_pipeline__x', 'num_pipeline__y',
       'num_pipeline__z', 'cat_pipeline__cut', 'cat_pipeline__color',
       'cat_pipeline__clarity'], dtype=object)

In [27]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [28]:

X_train

num_pipeline__carat  num_pipeline__depth  num_pipeline__table  \
0                 -0.975439            -0.849607            -0.121531   
1                  0.235195             1.833637            -0.121531   
2                  0.494617             0.815855             0.399800   
3                 -1.018676             0.260701             0.921131   
4                 -0.953821            -0.664555            -0.642862   
...                     ...                  ...                  ...   
135496            -1.040295            -0.016876            -0.642862   
135497             0.991842             0.168176            -0.642862   
135498             0.451380             1.556060            -0.642862   
135499             0.667565            -1.774863             1.442462   
135500             0.256814             0.815855            -0.121531   

        num_pipeline__x  num_pipeline__y  num_pipeline__z  cat_pipeline__cut  \
0             -1.042757        -1.080970        -1.123150                4.0   
1              0.318447         0.279859         0.485354                1.0   
2              0.570855         0.606458         0.673737                3.0   
3             -1.214034        -1.244270        -1.195605                3.0   
4             -1.069801        -1.044681        -1.094168                4.0   
...                 ...              ...              ...                ...   
135496        -1.268122        -1.244270        -1.239078                4.0   
135497         1.048629         1.114501         1.079486                4.0   
135498         0.516768         0.588314         0.702719                1.0   
135499         0.868337         0.951202         0.688228                4.0   
135500         0.381549         0.415942         0.470863                4.0   

        cat_pipeline__color  cat_pipeline__clarity  
0                       5.0                    5.0  
1                       1.0                    2.0  
2                       3.0                    4.0  
3                       3.0                    3.0  
4                       6.0                    5.0  
...                     ...                    ...  
135496                  1.0                    2.0  
135497                  3.0                    1.0  
135498                  3.0                    2.0  
135499                  3.0                    4.0  
135500                  3.0                    2.0  

[135501 rows x 9 columns]

In [ ]:
"linear regression"
"ridge regression"
"lasso regression"
"elastic net"

In [29]:
## Model Training

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [30]:
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [31]:
regression.coef_

array([ 6433.66003594,  -132.75843566,   -70.42922179, -1720.30971463,
        -499.29302619,   -63.39317848,    72.89534931,  -283.5924305 ,
         433.73822644])

In [32]:
regression.intercept_

np.float64(3168.2396920284855)

In [42]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [33]:
models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}

In [34]:
trained_model_list=[]
model_list=[]
r2_list=[]

In [35]:
list(models)

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [41]:
for i in range(len(list(models))):
    print(i)
    model=list(models.values())[i]
    print(model)

0
LinearRegression()
1
Lasso()
2
Ridge()
3
ElasticNet()


In [39]:
models.keys()

dict_keys(['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet'])

In [40]:
models.values()

dict_values([LinearRegression(), Lasso(), Ridge(), ElasticNet()])

In [43]:
## Train multiple models
## Model Ecaluation

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')


LinearRegression
Model Training Performance
RMSE: 1013.9047094344004
MAE: 674.0255115796833
R2 score 93.68908248567512


Lasso
Model Training Performance
RMSE: 1013.8723151049944
MAE: 675.2036880701621
R2 score 93.68948574778251


Ridge
Model Training Performance
RMSE: 1013.9058997761066
MAE: 674.056513229594
R2 score 93.68906766741327


Elasticnet
Model Training Performance
RMSE: 1513.914035022976
MAE: 1050.7468664314322
R2 score 85.92978759337907


